"""Run one contract-feedback revision over PHP SSRF repair outputs.

The feedback is generated by the deterministic source-level contract checker.
This is an exploratory experiment: without a PHP runtime it cannot establish
syntax or exploitability, so results must remain separate from SAFE_FIX labels.
"""
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

from safe2merge.agent import MODEL, _lang_ext, parse_fixed


def load_rows(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def load_checks(paths: list[Path]) -> dict[tuple[str, str], dict]:
    checks = {}
    for path in paths:
        for row in load_rows(path):
            source_name = Path(row.get("source", "")).name
            if source_name:
                checks[(source_name, row["cve_id"])] = row
    return checks


def feedback(check: dict | None) -> str:
    if not check:
        return (
            "No structured feedback is available. Produce a complete, minimal "
            "PHP SSRF repair and write fixed.php."
        )
    failed = [key for key, value in check["checks"].items() if value == "FAIL"]
    unknown = [key for key, value in check["checks"].items() if value == "UNKNOWN"]
    lines = [
        "Structured contract feedback from the previous candidate:",
        "The following properties are currently FAIL and must be fixed in code:",
    ]
    lines.extend(f"- {item}" for item in failed)
    if unknown:
        lines.append("These properties are UNKNOWN and must not be claimed without code evidence:")
        lines.extend(f"- {item}" for item in unknown)
    lines.extend(
        [
            "Do not merely describe the changes. Write the full corrected function/snippet.",
            "Do not add invented helpers or identifiers. Preserve existing behavior and APIs.",
            "A candidate that still passes the raw URL/hostname to a network sink is not acceptable.",
        ]
    )
    return "\n".join(lines)


def build_prompt(row: dict, contract: dict | None, ext: str) -> str:
    draft = row.get("agent_fixed") or ""
    return f"""You are performing a final code repair for {row['cve_id']} ({row['language']}).

The previous candidate is in `draft.{ext}`. Apply the structured contract feedback
below and write a corrected full function/snippet to `fixed.{ext}`.

{feedback(contract)}

Requirements:
- Only accept http/https where the original behavior requires remote URLs.
- Resolve and validate every relevant A/AAAA result.
- Reject loopback, private, link-local, multicast, unspecified, and IPv4-mapped targets.
- Connect or download through the approved destination rather than the raw user URL.
- Disable redirects or validate every redirect destination.
- Use only identifiers and APIs supported by the shown snippet/repository context.
- Do not turn the method into a no-op and do not add extra files.

===== VULNERABLE CODE =====
{row['vuln_code']}

===== PREVIOUS CANDIDATE =====
{draft or '(no usable previous candidate)'}
"""


def run_one(row: dict, contract: dict | None, workdir: Path, timeout_sec: int) -> dict:
    ext = _lang_ext(row["language"])
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / f"vuln.{ext}").write_text(row["vuln_code"], encoding="utf-8")
    (workdir / f"draft.{ext}").write_text(row.get("agent_fixed") or "", encoding="utf-8")
    note = feedback(contract)
    (workdir / "contract_feedback.txt").write_text(note, encoding="utf-8")
    prompt = build_prompt(row, contract, ext)
    cmd = ["opencode", "run", "--format", "json", "-m", MODEL, "--dir", str(workdir), prompt]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout_sec)
        raw = proc.stdout
        returncode = proc.returncode
    except subprocess.TimeoutExpired:
        raw = "<<TIMEOUT>>"
        returncode = None
    fixed, reply, tokens = parse_fixed(raw)
    return {
        "cve_id": row["cve_id"],
        "language": row["language"],
        "repo": row.get("repo", ""),
        "description": row.get("description", ""),
        "vuln_code": row["vuln_code"],
        "draft": row.get("agent_fixed") or "",
        "contract_feedback": note,
        "agent_fixed": fixed,
        "agent_reply": reply,
        "tokens": tokens,
        "returncode": returncode,
        "status": "TIMEOUT" if raw == "<<TIMEOUT>>" else ("OK" if fixed else "NO_WRITE"),
        "selected_model": MODEL,
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--in", dest="inp", required=True)
    ap.add_argument("--contracts", nargs="+", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--root", required=True)
    ap.add_argument("--timeout", type=int, default=300)
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="write prompts and feedback files without invoking opencode",
    )
    args = ap.parse_args()

    rows = load_rows(Path(args.inp))
    checks = load_checks([Path(item) for item in args.contracts])
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    done = {json.loads(line)["cve_id"] for line in out.read_text(encoding="utf-8").splitlines() if line.strip()} if out.exists() else set()
    todo = [row for row in rows if row["cve_id"] not in done]
    root = Path(args.root)
    root.mkdir(parents=True, exist_ok=True)
    print(f"rows {len(rows)} | already done {len(done)} | to run {len(todo)}")
    for index, row in enumerate(todo, 1):
        source_name = Path(args.inp).name
        contract = checks.get((source_name, row["cve_id"]))
        print(f"[{index}/{len(todo)}] {row['cve_id']} ...", flush=True)
        if args.dry_run:
            workdir = Path(args.root) / row["cve_id"]
            workdir.mkdir(parents=True, exist_ok=True)
            ext = _lang_ext(row["language"])
            prompt = build_prompt(row, contract, ext)
            (workdir / "contract_feedback.txt").write_text(feedback(contract), encoding="utf-8")
            (workdir / f"prompt.{ext}.txt").write_text(prompt, encoding="utf-8")
            result = {
                "cve_id": row["cve_id"],
                "language": row["language"],
                "repo": row.get("repo", ""),
                "description": row.get("description", ""),
                "vuln_code": row["vuln_code"],
                "draft": row.get("agent_fixed") or "",
                "contract_feedback": feedback(contract),
                "agent_fixed": None,
                "agent_reply": None,
                "tokens": 0,
                "returncode": None,
                "status": "DRY_RUN",
                "selected_model": MODEL,
            }
            with out.open("a", encoding="utf-8") as fh:
                fh.write(json.dumps(result, ensure_ascii=False) + "\n")
            print(json.dumps({"cve_id": row["cve_id"], "status": "DRY_RUN"}, ensure_ascii=False), flush=True)
            continue
        result = run_one(row, contract, root / row["cve_id"], args.timeout)
        with out.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(result, ensure_ascii=False) + "\n")
        print(json.dumps({k: result[k] for k in ("cve_id", "status", "tokens")}, ensure_ascii=False), flush=True)
    print(f"DONE -> {out}")


if __name__ == "__main__":
    main()
